# Generated by Django 2.1.5 on 2019-06-29 05:05

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', jsonfield.fields.JSONField(default=dict)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('descricao', models.CharField(choices=[('EXTERNA', 'Externa'), ('INTERNA', 'Interna')], default='INTERNA', max_length=10)),
                ('tempo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
