# Generated by Django 2.1.5 on 2019-06-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('descricao', models.CharField(choices=[('EXTERNA', 'Externa'), ('INTERNA', 'Interna')], default='INTERNA', max_length=10)),
                ('tempo', models.DateTimeField()),
            ],
        ),
    ]
