# Generated by Django 2.1.5 on 2019-06-29 04:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caixa_racional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', jsonfield.fields.JSONField(default=dict)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='tempo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
