# Generated by Django 2.1.5 on 2019-07-10 16:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caixa_racional', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basededados',
            old_name='dt_criacao',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='basededados',
            name='base',
            field=jsonfield.fields.JSONField(),
        ),
    ]
